### ISSUE TITLE
Corrupted file? - us_politics_dedup_[:100]_seed][1].txt

### ISSUE THREAD

**Issue by drob-xx** [dkorenci/topic_coverage#1]
Working on Windows and using Git Desktop I tried to clone the repository and kept getting an error with the mentioned file that prohibited a complete clone of the repository. The file looks ok when I browse to it in the repository. However, when I downloaded a zip of the repository and unziped - I got an 'unexpected' error on the same file. Don't know what the problem is.

**Comment by dkorenci** [comment]
The problem was that ':' is illegal character for Windows file names. I renamed the files in question (the only such files in the repo). Everything should work now. If the tests in question fail because old names are cached, just delete the resource cache, or ping me.
